<a href="https://colab.research.google.com/github/Deepika316/Mind_Wave_python/blob/main/Numpy_mindwave.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
#array creation
import numpy as np
a=np.array((1,2,3,4,5))
print("Array:",a)
b=np.arange(1,6)
print("Array creation using arrange:",b)
c=np.zeros((3,3))
print("Array creation using zeros:",c)
d=np.ones((3,3))
print("Array creation using ones:",d)
e=np.linspace(1,10,5)
print("Array creation using linspace:",e)
f=np.eye(3)
print("Array creation using eye:",f)
e=np.random.rand((3))
print("Array creation using random:",e)
f=np.random.randn((3))
print("Array creation using random normal:",f)
g=np.random.randint(1,10,5)
print("Array creation using random integer:",g)



Array: [1 2 3 4 5]
Array creation using arrange: [1 2 3 4 5]
Array creation using zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array creation using ones: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array creation using linspace: [ 1.    3.25  5.5   7.75 10.  ]
Array creation using eye: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Array creation using random: [0.60905593 0.49269601 0.28880873]
Array creation using random normal: [-0.54489436  1.81251124  0.38228962]
Array creation using random integer: [7 1 1 5 5]


In [13]:
#array attributes
import numpy as np
a=np.array([[1,2,3,4],[3,4,5,6]])
print("ndim:",a.ndim)
print("shape:",a.shape)
print("size:",a.size)
print("dtype:",a.dtype)
print("itemsize:",a.itemsize)
print("nbytes:",a.nbytes)
print("Transpose:",a.T)

ndim: 2
shape: (2, 4)
size: 8
dtype: int64
itemsize: 8
nbytes: 64
Transpose: [[1 3]
 [2 4]
 [3 5]
 [4 6]]


In [21]:
#aggregation functiions
import numpy as np
x=np.array([10,23,34,89])
print("sum:",np.sum(x))
print("mean:",x.mean())
print("minimum:",x.min())
print("Maximum:",x.max())
print("standard deviation:",x.std())
print("variance:",x.var())
#print("median:",x.median())
print(np.median(x))
print("product:",x.prod())



sum: 156
mean: 39.0
minimum: 10
Maximum: 89
standard deviation: 30.091527046662154
variance: 905.5
28.5
product: 695980


In [30]:
#Indexing,slicing,reshape
a=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(np.ndim(a))
print("Indexing:",a[0,2,2])
print("indexing:",a[:,:2,:2])
print("Slicing:",a[0,1,2:])
print("Reshape:",a.reshape(4,3))

3
Indexing: 11
indexing: [[[1 2]
  [5 6]]]
Slicing: [7 8]
Reshape: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
